name: Deploy Documentation CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  RID: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true

      - name: Validate Dependencies
        id: validate-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.validate-dependencies.outputs.cache-hit != 'true'
        run: yarn

      - name: Cache Dependencies
        uses: actions/cache@v2
        if: steps.validate-dependencies.outputs.cache-hit != 'true'
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

  transpile:
    name: Transpile
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true

      - name: Uncache Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Build - Loose
        run: yarn build:loose

      - name: Cache Dist
        uses: actions/cache@v2
        with:
          path: dist/
          key: dist-${{ runner.os }}-${{ env.RID }}

  generate-documentation:
    name: Generate - Documentation
    needs: transpile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true

      - name: Uncache Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Uncache Dist
        uses: actions/cache@v2
        with:
          path: dist/
          key: dist-${{ runner.os }}-${{ env.RID }}

      - name: Build - Docs Data
        run: yarn build:docs:data

      - name: Build - Docs Dist
        run: yarn build:docs:dist

      - name: Cache Docs
        uses: actions/cache@v2
        with:
          path: docs/
          key: docs-${{ runner.os }}-${{ env.RID }}

  deploy-documentation:
    name: Deploy - Documentation
    needs: generate-documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: documentation

      - name: Clean Documentation
        run: |
          rm -rf ./docs

      - name: Uncache Documentation
        uses: actions/cache@v2
        with:
          path: docs/
          key: docs-${{ runner.os }}-${{ env.rid }}

      - name: Deploy Documentation
        run: |
          git config --global user.name "Automation"
          git config --global user.email "automation@alboe.dev"
          git add ./docs
          FILE_COUNT=$(git status -s | wc -l | xargs)
          if [[ $FILE_COUNT != '0' ]]
          then
            echo "Found $FILE_COUNT changed documentation files."
            echo "Publishing documentation changes."
            git commit -m "ci(docs): deploy documentation [skip ci]"
            git push origin documentation
          else
            echo "Documentation files have not changed."
            echo "Documentation will not be published."
          fi